// Marathi translations, keyed by the English text used in the UI.
export default {
  // navigation / layout
  'Storefront Ratings': 'स्टोअरफ्रंट रेटिंग्ज',
  'Stores': 'दुकाने',
  'Dashboard': 'डॅशबोर्ड',
  'Analytics': 'विश्लेषण',
  'Change password': 'पासवर्ड बदला',
  'Log out': 'लॉग आउट',
  'Administrator': 'प्रशासक',
  'Member': 'सदस्य',
  'Store owner': 'दुकान मालक',
  'Admin': 'प्रशासक',
  'Normal user': 'सामान्य वापरकर्ता',
  // auth
  'Log in': 'लॉग इन',
  'Members, store owners and administrators all sign in here.': 'सदस्य, दुकान मालक आणि प्रशासक सर्वजण येथे लॉग इन करतात.',
  'Email': 'ईमेल',
  'Password': 'पासवर्ड',
  'Logging in…': 'लॉग इन होत आहे…',
  'New here?': 'नवीन आहात का?',
  'Create an account': 'खाते तयार करा',
  'Create your account': 'तुमचे खाते तयार करा',
  'Full name (20-60 characters)': 'पूर्ण नाव (२०-६० अक्षरे)',
  'Address (max 400 characters)': 'पत्ता (कमाल ४०० अक्षरे)',
  'Password (8-16 characters, one capital, one symbol)': 'पासवर्ड (८-१६ अक्षरे, एक कॅपिटल अक्षर, एक चिन्ह)',
  'Creating…': 'तयार होत आहे…',
  'Sign up': 'नोंदणी करा',
  'Already registered?': 'आधीच नोंदणी केली आहे?',
  'Current password': 'सध्याचा पासवर्ड',
  'New password': 'नवीन पासवर्ड',
  'Update password': 'पासवर्ड अपडेट करा',
  'Password updated.': 'पासवर्ड अपडेट झाला.',
  // messages and validation
  'Name must be 20-60 characters': 'नाव २०-६० अक्षरांचे असावे',
  'Enter a valid email address': 'योग्य ईमेल पत्ता टाका',
  'Address is required (max 400 characters)': 'पत्ता आवश्यक आहे (कमाल ४०० अक्षरे)',
  'Use 8-16 characters with one uppercase letter and one special character': '८-१६ अक्षरे वापरा; त्यात एक कॅपिटल अक्षर आणि एक विशेष चिन्ह असावे',
  'Password must be 8-16 characters with one uppercase letter and one special character': 'पासवर्ड ८-१६ अक्षरांचा असावा; त्यात एक कॅपिटल अक्षर आणि एक विशेष चिन्ह असावे',
  'Enter your current password': 'सध्याचा पासवर्ड टाका',
  'Current password is incorrect': 'सध्याचा पासवर्ड चुकीचा आहे',
  'Incorrect email or password': 'ईमेल किंवा पासवर्ड चुकीचा आहे',
  'Email and password are required': 'ईमेल आणि पासवर्ड आवश्यक आहेत',
  'Email already exists': 'हा ईमेल आधीच वापरात आहे',
  'Validation failed': 'माहिती तपासणीत चूक आढळली',
  'Something went wrong. Please try again.': 'काहीतरी चूक झाली. कृपया पुन्हा प्रयत्न करा.',
  'Select a valid store owner': 'योग्य दुकान मालक निवडा',
  'This owner already has a store': 'या मालकाचे आधीच एक दुकान आहे',
  'Choose a role': 'भूमिका निवडा',
  'Saved.': 'जतन केले.',
  'Loading…': 'लोड होत आहे…',
  'Nothing to show yet.': 'अजून काहीही दाखवण्यासारखे नाही.',
  // stores (user)
  'Search by store name': 'दुकानाच्या नावाने शोधा',
  'Search by address': 'पत्त्याने शोधा',
  'Store': 'दुकान',
  'Address': 'पत्ता',
  'Overall rating': 'एकूण रेटिंग',
  'Your rating': 'तुमचे रेटिंग',
  'Ranking score': 'क्रमवारी गुण',
  'Click a star to change': 'बदलण्यासाठी तारा निवडा',
  'Not rated yet': 'अजून रेटिंग दिलेले नाही',
  'No stores match your search.': 'तुमच्या शोधाशी जुळणारे दुकान नाही.',
  'Top ranked first': 'सर्वोत्तम आधी',
  "Ranking score balances a store's average rating with how many people rated it.": 'क्रमवारी गुण हे दुकानाचे सरासरी रेटिंग आणि किती लोकांनी रेटिंग दिले, यांचा समतोल साधतात.',
  'No ratings yet': 'अजून रेटिंग नाही',
  'ratings': 'रेटिंग्ज',
  // owner
  'No store is linked to your account yet. Ask an administrator to assign one.': 'तुमच्या खात्याशी अजून कोणतेही दुकान जोडलेले नाही. प्रशासकाला दुकान नेमायला सांगा.',
  'Average rating': 'सरासरी रेटिंग',
  'Ratings received': 'मिळालेली रेटिंग्ज',
  'Customers who rated your store': 'तुमच्या दुकानाला रेटिंग देणारे ग्राहक',
  'Name': 'नाव',
  'Rating': 'रेटिंग',
  'Rated on': 'रेटिंग दिनांक',
  'No one has rated your store yet.': 'अजून कोणीही तुमच्या दुकानाला रेटिंग दिलेले नाही.',
  // admin
  'Total users': 'एकूण वापरकर्ते',
  'Total stores': 'एकूण दुकाने',
  'Ratings submitted': 'सादर केलेली रेटिंग्ज',
  'Users': 'वापरकर्ते',
  'Role': 'भूमिका',
  'Score': 'गुण',
  'Filter by name': 'नावाने फिल्टर करा',
  'Filter by email': 'ईमेलने फिल्टर करा',
  'Filter by address': 'पत्त्याने फिल्टर करा',
  'Filter by role': 'भूमिकेने फिल्टर करा',
  'All roles': 'सर्व भूमिका',
  'Add user': 'वापरकर्ता जोडा',
  'Add store': 'दुकान जोडा',
  'Close form': 'फॉर्म बंद करा',
  'Close': 'बंद करा',
  'Name (20-60 characters)': 'नाव (२०-६० अक्षरे)',
  'Store name (20-60 characters)': 'दुकानाचे नाव (२०-६० अक्षरे)',
  'Store email': 'दुकानाचा ईमेल',
  'Store owner (optional)': 'दुकान मालक (ऐच्छिक)',
  'No owner assigned': 'मालक नेमलेला नाही',
  'Store rating': 'दुकानाचे रेटिंग',
  'No users match these filters.': 'या फिल्टरशी जुळणारा वापरकर्ता नाही.',
  'No stores match these filters.': 'या फिल्टरशी जुळणारे दुकान नाही.',
  // analytics
  'Ratings per day': 'दररोजची रेटिंग्ज',
  'Period': 'कालावधी',
  '7 days': '७ दिवस',
  '14 days': '१४ दिवस',
  '30 days': '३० दिवस',
  'Top-rated stores': 'सर्वोत्तम रेटिंगची दुकाने',
  'Most active users': 'सर्वात सक्रिय वापरकर्ते',
  'Ratings given': 'दिलेली रेटिंग्ज',
  'Average given': 'दिलेली सरासरी',
  'Rating breakdown': 'रेटिंग विभागणी',
  'Ratings count': 'रेटिंगची संख्या',
  'No ratings have been submitted yet.': 'अजून एकही रेटिंग सादर केलेले नाही.',
  'No activity yet.': 'अजून कोणतीही हालचाल नाही.',
};
